### ISSUE TITLE
Require C++11?

### ISSUE THREAD

**Issue by pdimov** [boostorg/optional#109]
A number of libraries have [announced that they will require C++11 starting from 1.84](https://www.boost.org/users/history/version_1_82_0.html).

Will Optional do that as well? (Such deprecations need to be announced two releases in advance.)

This will allow simplifications and enable getting rid of some of the current dependencies.

**Comment by akrzemi1** [comment]
I have no plans to drop support for C++03, as I have no strong motivation.
Indeed, the implementation of Boost.Optional would be much simpler if I required C++11, but I did not find this alone sufficient a motivation.
Is leaving Boost.Optional as is causing problems for other libraries?

**Comment by pdimov** [comment]
No serious problems as such.

The gain would mostly come as reduced number of dependencies. Currently Boost.Optional has [12 dependencies](https://pdimov.github.io/boostdep-report/develop/module-weights.html#weight:12) which is sometimes an impediment for other (C++11 but pre-C++17) libraries that could use it in their interfaces.

**Comment by akrzemi1** [comment]
Regarding the dependencies, Boost.Optional depends on Boost.Utility because it provides the InPlaceFactory and OptionalPoinees. This is a piece of functionality, so I would have to drop some portions of the interface. InPlaceFactory is not needed in C++11 anymore, but might break somebody's code. OptionalPointees is implementaiton detail, but it followed a good practice of abstracting the concepts for reuse in other components.

**Comment by akrzemi1** [comment]
https://github.com/boostorg/optional/commit/bf58a919dfd7abe0d79ad802a4c93791a05aebd5

**Comment by akrzemi1** [comment]
Dropped support for C++03 in develop.

**Comment by akrzemi1** [comment]
And now in master.
