### ISSUE TITLE
Is the boost::optional interface backwards compatible?

### ISSUE THREAD

**Issue by mg262** [boostorg/optional#32]
I am creating a library that returns `boost::optional<string>`s.  If I develop against `boost::optional` 1.62, and users try to use a later version of `boost::optional`, what will happen?

**Comment by fcacciola** [comment]
Future versions of boost::optional will be backward-compatible.
However, we now have std::optional, and is available in some newest compilers such as Visual Studio 2017. so, if you are just starting to use this, it might be better to adopt the std version if you can.

**Comment by mg262** [comment]
Further to this -- we've built a library against boost::optional 1.62, but some of the targets that need to be built against the library may have trouble using that recent a v. of boost.  Was there any point in the _past_ development of boost when there would have been an incompatibility? E.g. if users use boost::optional 1.0.0, would that cause an issue?
  (Thanks!)

**Comment by akrzemi1** [comment]
There were slight changes that may render some previous code invalid. For instance, in pre-C++11 versions conversion to bool was not explicit, and the following was possible:
```c++
optional<T> o;
bool b = o;
``` 
This will now not compile, and we consider it a positive breaking change. 

Similarly, the addition of move semantics to `boost::optional` caused some rare code to fail to compile on older MSVC versions that implemented move semantics incorrectly.

Also, the implementation of optional references worked incorrectly on some compilers due to compiler bugs. Now in order to avoid bugs, on this compilers run-time bugs have been turned into compile-time failures.

But in general our goal is not to change the interface. Even deprecated functions are not removed.  Any regressions if present are unintentional.

**Comment by mg262** [comment]
Thank you very much for this detailed reply.
