### ISSUE TITLE
make_optional broken with optional references

### ISSUE THREAD

**Issue by MerryMage** [boostorg/optional#45]
c695be1 breaks this use-case.

Please see below for a minimal testcase.

    #include <boost/optional.hpp>
    
    struct Foo {};

    Foo f;

    Foo create_a_foo() {
        return {};
    }

    boost::optional<Foo&> frob() {
        return boost::make_optional<Foo&>(create_a_foo());
    }

    int main(){}

**Comment by akrzemi1** [comment]
What do you expect of this test case? That it should compile?

**Comment by MerryMage** [comment]
Yes.

**Comment by akrzemi1** [comment]
But you are creating a temporary `Foo` inside function `forb` if you tie it to a reference, and return this reference outside function `forb` the temporary object will by then have been destroyed, and your reference is dangling, which will cause UB as soon as you will try to dereference it. I think it is a good safety feature that this bug is detected and reported at compile-time.

**Comment by MerryMage** [comment]
I do apologise, I wasn't thinking properly regarding that test-case. See below for a better example.

    #include <array>
    #include <cstddef>
    #include <boost/optional.hpp>

    struct Foo {};

    boost::optional<const Foo&> frob(std::size_t i) {
        static const std::array<Foo, 3> a = {{}, {}, {}};
        return boost::make_optional<const Foo&>(a[i]);
    }

**Comment by akrzemi1** [comment]
Ok, but are you not using `make_optional` like that? The goal of using it is to deduce the `T`. If you are specifying it anyway, why not just type:

```c++
boost::optional<const Foo&> frob(std::size_t i) {
    static const std::array<Foo, 3> a = {{}, {}, {}};
    return boost::optional<const Foo&>(a[i]);
}
```
? (which is shorter)

**Comment by MerryMage** [comment]
That's a fair point. Thanks for your time.
